Fix dynamic_config definition in Makefile.PL
ThisUsedToBeAnEmail/String-Mask pull request #4
Opened 2020-10-26 20:19 UTC by haarg

dynamic_config is a meta key, not a EUMM configuration option. Move it into a `META_MERGE` section.

Fixes #1

2020-10-26 20:19 UTC, Grinnz commented
meta-spec 2 should be specified when setting dynamic_config 0 since the meta-spec 1 meaning was different.

2020-10-26 20:20 UTC, Grinnz commented
it also needs compatibility to remove META_MERGE for old EUMM

2020-10-26 21:40 UTC, Grinnz requested changes

2020-10-26 21:40 UTC, Grinnz commented on Makefile.PL
> +        dynamic_config => 0,
needs `'meta-spec' => { version => 2 },`

2020-10-26 21:40 UTC, Grinnz commented on Makefile.PL
>  # Compatibility with old versions of ExtUtils::MakeMaker
```
delete $WriteMakefileArgs{META_MERGE}
  unless eval { ExtUtils::MakeMaker->VERSION('6.46'); 1 };
```

2020-10-27 06:29 UTC, ThisUsedToBeAnEmail commented
Thanks for guidance, this should now be resolved.

2020-10-27 06:29 UTC, closed without merging